services:
  - type: web
    name: youtube-viewer
    env: python
    region: singapore
    plan: free
    buildCommand: bash render-build.sh
    startCommand: bash render-start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DISPLAY
        value: :99
